# Generated by Django 5.1.4 on 2025-01-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_maintenance_status_alter_rentpayment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='room_no',
            field=models.CharField(default='Room 1', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Empty', 'Empty'), ('Booked', 'Booked')], default='Empty', max_length=10),
        ),
    ]
