# Generated by Django 5.1.4 on 2025-01-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_property_address_property_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
    ]
