# Generated by Django 5.1.4 on 2025-01-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_booking_booking_date_booking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myApp.booking'),
        ),
    ]
