# Generated by Django 5.1.4 on 2025-01-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_rentpayment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success')], default='Pending', max_length=10),
        ),
    ]
