# Generated by Django 5.1.4 on 2025-01-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_user_role_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='lease_details',
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
